name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build